#define TWI_MASTER_CTRLA      TWIC.MASTER.CTRLA
#define TWI_MASTER_CTRLB      TWIC.MASTER.CTRLB
#define TWI_MASTER_CTRLC      TWIC.MASTER.CTRLC
#define TWI_MASTER_STATUS     TWIC.MASTER.STATUS
#define TWI_MASTER_BAUD       TWIC.MASTER.BAUD
#define TWI_MASTER_ADDRESS    TWIC.MASTER.ADDRESS
#define TWI_MASTER_DATA       TWIC.MASTER.DATA